### ISSUE TITLE
Pytest deprecation issues with django-rest-framework-jwt

### ISSUE THREAD

**Issue by elliotyim** [devv-up/backend#42]
현재 rest-auth와 함께 사용하고 있는 jwt 라이브러리는 `django-rest-framework-jwt`입니다.
이번에 #41 hotfix 작업을 하면서 jwt 라이브러리에 있는 jwt 토큰을 생성하는 util을 사용하다보니
라이브러리에서 Deprecated된 모듈을 사용하는 부분 때문에 Deprecation Warning이 발생했습니다.

이 라이브러리는 현재 유지보수를 중단했으며, 다행히 다른 JWT 라이브러리로 교체가 가능한 것 같습니다.
(참고: https://github.com/jpadilla/django-rest-framework-jwt/issues/484)

후속 PR에서 이 라이브러리를 교체하는 작업이 필요합니다.

**Comment by choitaehoon1998** [comment]
참고올리신 링크에서는 simple jwt를 대안으로 추천해놓은 모양인데 그걸로 바꾸면 될까요?

**Comment by elliotyim** [comment]
> 참고올리신 링크에서는 simple jwt를 대안으로 추천해놓은 모양인데 그걸로 바꾸면 될까요?

넵 추후 유지보수 및 보안 측면에서도 그게 좋지 않을까 싶습니다.
